CFLAGS += -std=c99 -Wall -Wextra -pedantic -O2 -g

all: bcproxy test_parser

.PHONY: clean

tags: *.c
	ctags -R --c++-kinds=+pl --c-kinds=+cdefmgpstux --fields=+iaS --extra=+q
cscope.out: *.c
	cscope -bR

OBJS = parser.o proxy.o buffer.o room.o color.o db.o

test_parser: test_parser.o $(OBJS)
	$(CC) -o $@ $@.o $(OBJS) $(LDFLAGS)

bcproxy: bcproxy.o $(OBJS)
	$(CC) -o $@ $@.o $(OBJS) $(LDFLAGS)

clean:
	rm -f test_parser bcproxy *.o
